<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BudgetData\ApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Budget Data
 *
 * API for persisting [budget data](https://github.com/forevermatt/budget-data)
 *
 * OpenAPI spec version: 0.1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.24
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BudgetData\ApiClient;

use BudgetData\ApiClient\Configuration;
use BudgetData\ApiClient\ApiException;
use BudgetData\ApiClient\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  BudgetData\ApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for accountsGet
     *
     * List the current user's (financial) Accounts.
     *
     */
    public function testAccountsGet()
    {
    }

    /**
     * Test case for accountsPost
     *
     * Add an account.
     *
     */
    public function testAccountsPost()
    {
    }
}
